services:

  database:
    build:
      context: "."
      dockerfile: ./database/Dockerfile
    image: benjaminpochat/viandeendirect-database:${DOCKER_IMAGE_TAG:-latest}
    volumes:
      - ${postgres_datafile_path:-./data}:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U viandeendirect"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${postgres_password:-p4ssw0rd}
      - VIANDEENDIRECT_PASSWORD=${backend_database_password:-vndndrct-db-p4ssw0rd}
      - IDENTITY_PASSWORD=${identity_database_password:-dntt-db-p4ssw0rd}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - ${postgres_port:-5432}:5432
    network_mode: "host"

  identity:
    build:
      context: "."
      dockerfile: ./identity/Dockerfile
    image: benjaminpochat/viandeendirect-identity:${DOCKER_IMAGE_TAG:-latest}
    depends_on:
      database:
        condition: service_healthy
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=${keycloak_admin_password:-admin}
      #- KEYCLOAK_IMPORT=/opt/keycloak/realm/realm.json
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://database:5432/identity
      - KC_DB_USERNAME=identity
      - KC_DB_PASSWORD=${identity_database_password:-dntt-db-p4ssw0rd}
      - KC_HOSTNAME_URL=${identity_url:-http://localhost:8180}
      - KC_HOSTNAME_ADMIN_URL=${identity_url:-http://localhost:8180}
      - KC_HEALTH_ENABLED=true
      - KC_PROXY=edge
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/health || exit 1" ]
      interval: 5s
      timeout: 60s
      retries: 5
    command: start-dev
    ports:
      - ${identity_port:-8180}:8080
    network_mode: "host"

  backend:
    build:
      context: "."
      dockerfile: ./backend/Dockerfile
    image: benjaminpochat/viandeendirect-backend:${DOCKER_IMAGE_TAG:-latest}
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/viandeendirect
      - SPRING_DATASOURCE_USERNAME=viandeendirect
      - SPRING_DATASOURCE_PASSWORD=${backend_database_password:-vndndrct-db-p4ssw0rd}
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=${identity_url:-http://localhost:8180}/realms/viandeendirect
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=${identity_url:-http://localhost:8180}/realms/viandeendirect
      - SPRING_PROFILES_ACTIVE=oauth,postgre
    depends_on:
      database:
        condition: service_healthy
      identity:
        condition: service_healthy
    ports:
      - ${backend_port:-8080}:8080
    network_mode: "host"

  frontend-producer:
    build:
      context: "."
      dockerfile: ./frontend/Dockerfile
      args:
        REACT_APP_MODE: PRODUCER
    image: benjaminpochat/viandeendirect-frontend-producer:${DOCKER_IMAGE_TAG:-latest}
    volumes:
      - ${frontend_producer_config_path:-./frontend-producer-config}:/usr/local/apache2/htdocs/config
    ports:
      - ${frontend_producer_port:-81}:80
    network_mode: "host"

  frontend-customer:
    build:
      context: "."
      dockerfile: ./frontend/Dockerfile
      args:
        REACT_APP_MODE: CUSTOMER
    image: benjaminpochat/viandeendirect-frontend-customer:${DOCKER_IMAGE_TAG:-latest}
    volumes:
      - ${frontend_customer_config_path:-./frontend-customer-config}:/usr/local/apache2/htdocs/config
    ports:
      - ${frontend_customer_port:-80}:80
    network_mode: "host"
