services:

  database:
    build:
      context: "."
      dockerfile: ./database/Dockerfile
    image: benjaminpochat/viandeendirect-database:${DOCKER_IMAGE_TAG:-latest}
    volumes:
      - ${postgres_datafile_path:-./data}:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${postgres_password:-p4ssw0rd}
      - VIANDEENDIRECT_PASSWORD=${backend_database_password:-vndndrct-db-p4ssw0rd}
      - IDENTITY_PASSWORD=${identity_database_password:-dntt-db-p4ssw0rd}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - ${postgres_port:-5432}:5432

  identity:
    #image: quay.io/keycloak/keycloak:21.0.1
    build:
      context: "."
      dockerfile: ./identity/Dockerfile
    image: benjaminpochat/viandeendirect-identity:${DOCKER_IMAGE_TAG:-latest}
    depends_on:
      - database
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=${keycloak_admin_password:-admin}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://database:${postgres_port:-5432}/identity
      - KC_DB_USERNAME=identity
      - KC_DB_PASSWORD=${identity_database_password:-dntt-db-p4ssw0rd}
      - KC_HOSTNAME=localhost
    command: start-dev
    ports:
      - ${keycloak_port:-8180}:8080

  backend:
    build:
      context: "."
      dockerfile: ./backend/Dockerfile
    image: benjaminpochat/viandeendirect-backend:${DOCKER_IMAGE_TAG:-latest}
    depends_on:
      - database
      - identity
    ports:
      - ${backend_port:-8080}:8080
