openapi: 3.0.2
info:
  description: This API allows selling and buying food through the shortest path between
    farmers and customers.
  title: viandeendirect.eu
  version: 0.0.1
servers:
- url: /
paths:
  /deliveries:
    get:
      description: Retreive the deliveries available for buying food. The past deliveries
        are excluded.
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Delivery'
                type: array
          description: The deliveries are retreived
      summary: Get all deliveries
      x-accepts: application/json
components:
  schemas:
    Address:
      properties:
        id:
          type: UUID
          x-field-extra-annotation: '@jakarta.persistence.Id'
        name:
          type: string
        city:
          type: string
        addressLine1:
          type: string
        addressLine2:
          type: string
        addressLine3:
          type: string
        addressLine4:
          type: string
      x-class-extra-annotation: '@jakarta.persistence.Entity @jakarta.persistence.Table(name
        = "adresses")'
    Delivery:
      example:
        deliveryAddress: ""
        name: name
        id: ""
      properties:
        id:
          type: UUID
          x-field-extra-annotation: '@jakarta.persistence.Id'
        name:
          type: string
        deliveryAddress:
          type: Address
          x-field-extra-annotation: '@jakarta.persistence.OneToOne'
      x-class-extra-annotation: '@jakarta.persistence.Entity @jakarta.persistence.Table(name
        = "deliveries")'
