/**
 * viandeendirect.eu
 * This API allows selling and buying food through the shortest path between farmers and customers.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Address from './Address';

/**
 * The Delivery model module.
 * @module model/Delivery
 * @version 0.0.1
 */
class Delivery {
    /**
     * Constructs a new <code>Delivery</code>.
     * @alias module:model/Delivery
     */
    constructor() { 
        
        Delivery.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Delivery</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Delivery} obj Optional instance to populate.
     * @return {module:model/Delivery} The populated <code>Delivery</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Delivery();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('deliveryAddress')) {
                obj['deliveryAddress'] = ApiClient.convertToType(data['deliveryAddress'], Address);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Delivery</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Delivery</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
Delivery.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Delivery.prototype['name'] = undefined;

/**
 * @member {module:model/Address} deliveryAddress
 */
Delivery.prototype['deliveryAddress'] = undefined;






export default Delivery;

