/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.2.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package eu.viandeendirect.api;

import eu.viandeendirect.model.Delivery;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-01-29T16:21:14.967495596+01:00[Europe/Paris]")
@Validated
@Tag(name = "deliveries", description = "the deliveries API")
public interface DeliveriesApi {

    default DeliveriesApiDelegate getDelegate() {
        return new DeliveriesApiDelegate() {};
    }

    /**
     * GET /deliveries : Get all deliveries
     * Retreive the deliveries available for buying food. The past deliveries are excluded.
     *
     * @return The deliveries are retreived (status code 200)
     */
    @Operation(
        operationId = "deliveriesGet",
        summary = "Get all deliveries",
        responses = {
            @ApiResponse(responseCode = "200", description = "The deliveries are retreived", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Delivery.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/deliveries",
        produces = { "application/json" }
    )
    default ResponseEntity<List<Delivery>> deliveriesGet(
        
    ) {
        return getDelegate().deliveriesGet();
    }

}
