package eu.viandeendirect.model;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonValue;
import eu.viandeendirect.model.BeefProduction;
import eu.viandeendirect.model.Lot;
import eu.viandeendirect.model.Producer;
import eu.viandeendirect.model.Production;
import eu.viandeendirect.model.Sale;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;


import java.util.*;
import jakarta.annotation.Generated;

/**
 * 
 */

@Schema(name = "BeefProduction", description = "")
@JsonIgnoreProperties(
  value = "productionType", // ignore manually set productionType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the productionType to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "productionType", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = BeefProduction.class, name = "BeefProduction")
})

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@jakarta.persistence.Entity @jakarta.persistence.Table(name = "beef_productions")
public class BeefProduction extends Production {

  @JsonProperty("animalIdentifier")
  private String animalIdentifier;

  @JsonProperty("animalLiveWeight")
  private BigDecimal animalLiveWeight;

  @JsonProperty("slaughterDate")
  private String slaughterDate;

  @JsonProperty("birthDate")
  private String birthDate;

  @JsonProperty("birthPlace")
  private String birthPlace;

  public BeefProduction animalIdentifier(String animalIdentifier) {
    this.animalIdentifier = animalIdentifier;
    return this;
  }

  /**
   * official identifier of the animal
   * @return animalIdentifier
  */
  
  @Schema(name = "animalIdentifier", description = "official identifier of the animal", required = false)
  public String getAnimalIdentifier() {
    return animalIdentifier;
  }

  public void setAnimalIdentifier(String animalIdentifier) {
    this.animalIdentifier = animalIdentifier;
  }

  public BeefProduction animalLiveWeight(BigDecimal animalLiveWeight) {
    this.animalLiveWeight = animalLiveWeight;
    return this;
  }

  /**
   * weight of the animal before being killed, in kilograms
   * @return animalLiveWeight
  */
  @Valid 
  @Schema(name = "animalLiveWeight", description = "weight of the animal before being killed, in kilograms", required = false)
  public BigDecimal getAnimalLiveWeight() {
    return animalLiveWeight;
  }

  public void setAnimalLiveWeight(BigDecimal animalLiveWeight) {
    this.animalLiveWeight = animalLiveWeight;
  }

  public BeefProduction slaughterDate(String slaughterDate) {
    this.slaughterDate = slaughterDate;
    return this;
  }

  /**
   * date when the animal has being killed
   * @return slaughterDate
  */
  
  @Schema(name = "slaughterDate", description = "date when the animal has being killed", required = false)
  public String getSlaughterDate() {
    return slaughterDate;
  }

  public void setSlaughterDate(String slaughterDate) {
    this.slaughterDate = slaughterDate;
  }

  public BeefProduction birthDate(String birthDate) {
    this.birthDate = birthDate;
    return this;
  }

  /**
   * date when the animal is born
   * @return birthDate
  */
  
  @Schema(name = "birthDate", description = "date when the animal is born", required = false)
  public String getBirthDate() {
    return birthDate;
  }

  public void setBirthDate(String birthDate) {
    this.birthDate = birthDate;
  }

  public BeefProduction birthPlace(String birthPlace) {
    this.birthPlace = birthPlace;
    return this;
  }

  /**
   * place where the animal is born
   * @return birthPlace
  */
  
  @Schema(name = "birthPlace", description = "place where the animal is born", required = false)
  public String getBirthPlace() {
    return birthPlace;
  }

  public void setBirthPlace(String birthPlace) {
    this.birthPlace = birthPlace;
  }

  public BeefProduction productionType(ProductionTypeEnum productionType) {
    super.setProductionType(productionType);
    return this;
  }

  public BeefProduction id(BigDecimal id) {
    super.setId(id);
    return this;
  }

  public BeefProduction sales(List<Sale> sales) {
    super.setSales(sales);
    return this;
  }

  public BeefProduction addSalesItem(Sale salesItem) {
    super.addSalesItem(salesItem);
    return this;
  }

  public BeefProduction producer(Producer producer) {
    super.setProducer(producer);
    return this;
  }

  public BeefProduction lots(List<Lot> lots) {
    super.setLots(lots);
    return this;
  }

  public BeefProduction addLotsItem(Lot lotsItem) {
    super.addLotsItem(lotsItem);
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BeefProduction beefProduction = (BeefProduction) o;
    return Objects.equals(this.animalIdentifier, beefProduction.animalIdentifier) &&
        Objects.equals(this.animalLiveWeight, beefProduction.animalLiveWeight) &&
        Objects.equals(this.slaughterDate, beefProduction.slaughterDate) &&
        Objects.equals(this.birthDate, beefProduction.birthDate) &&
        Objects.equals(this.birthPlace, beefProduction.birthPlace) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(animalIdentifier, animalLiveWeight, slaughterDate, birthDate, birthPlace, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BeefProduction {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    animalIdentifier: ").append(toIndentedString(animalIdentifier)).append("\n");
    sb.append("    animalLiveWeight: ").append(toIndentedString(animalLiveWeight)).append("\n");
    sb.append("    slaughterDate: ").append(toIndentedString(slaughterDate)).append("\n");
    sb.append("    birthDate: ").append(toIndentedString(birthDate)).append("\n");
    sb.append("    birthPlace: ").append(toIndentedString(birthPlace)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

