package eu.viandeendirect.model;

import java.net.URI;
import java.util.Objects;

import com.fasterxml.jackson.annotation.*;
import eu.viandeendirect.model.BeefProduction;
import eu.viandeendirect.model.PackageLot;
import eu.viandeendirect.model.Producer;
import eu.viandeendirect.model.Production;
import eu.viandeendirect.model.Sale;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.springframework.format.annotation.DateTimeFormat;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;


import java.util.*;
import jakarta.annotation.Generated;

/**
 * a production a beef meet, obtained by slaughtering and cutting an entire animal
 */

@Schema(name = "BeefProduction", description = "a production a beef meet, obtained by slaughtering and cutting an entire animal")
@JsonIgnoreProperties(
  value = "productionType", // ignore manually set productionType, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the productionType to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "productionType", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = BeefProduction.class, name = "BeefProduction")
})

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@jakarta.persistence.Entity @jakarta.persistence.Table(name = "beef_productions")
public class BeefProduction extends Production {

  @JsonProperty("animalIdentifier")
  private String animalIdentifier;

  /**
   * type of animal
   */
  public enum AnimalTypeEnum {
    COW("BEEF_COW"),
    
    HEIFER("BEEF_HEIFER"),
    
    BULL("BEEF_BULL"),
    
    VEAL("BEEF_VEAL");

    private String value;

    AnimalTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AnimalTypeEnum fromValue(String value) {
      for (AnimalTypeEnum b : AnimalTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("animalType")
  private AnimalTypeEnum animalType;

  /**
   * breed of the animal
   */
  public enum CattleBreedEnum {
    LIMOUSINE("LIMOUSINE"),

    CHAROLAISE("CHAROLAISE");

    private String value;

    CattleBreedEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CattleBreedEnum fromValue(String value) {
      for (CattleBreedEnum b : CattleBreedEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("cattleBreed")
  private CattleBreedEnum cattleBreed;

  @JsonProperty("birthDate")
  @DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
  private LocalDate birthDate;

  @JsonProperty("birthPlace")
  private String birthPlace;

  @JsonProperty("birthFarm")
  private String birthFarm;

  @JsonProperty("warmCarcassWeight")
  private Integer warmCarcassWeight;

  @JsonProperty("meatWeight")
  private Integer meatWeight;

  @JsonProperty("slaughterDate")
  @DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
  private LocalDate slaughterDate;

  @JsonProperty("slaughterPlace")
  private String slaughterPlace;

  @JsonProperty("slaughterHouse")
  private String slaughterHouse;

  @JsonProperty("cuttingDate")
  private String cuttingDate;

  @JsonProperty("cuttingPlace")
  private String cuttingPlace;

  @JsonProperty("cuttingButcher")
  private String cuttingButcher;

  @JsonProperty("labelRougeCertified")
  private Boolean labelRougeCertified;

  public BeefProduction animalIdentifier(String animalIdentifier) {
    this.animalIdentifier = animalIdentifier;
    return this;
  }

  /**
   * official identifier of the animal
   * @return animalIdentifier
  */
  
  @Schema(name = "animalIdentifier", description = "official identifier of the animal", required = false)
  public String getAnimalIdentifier() {
    return animalIdentifier;
  }

  public void setAnimalIdentifier(String animalIdentifier) {
    this.animalIdentifier = animalIdentifier;
  }

  public BeefProduction animalType(AnimalTypeEnum animalType) {
    this.animalType = animalType;
    return this;
  }

  /**
   * type of animal
   * @return animalType
  */

  @Schema(name = "animalType", description = "type of animal", required = false)
  public AnimalTypeEnum getAnimalType() {
    return animalType;
  }

  public void setAnimalType(AnimalTypeEnum animalType) {
    this.animalType = animalType;
  }

  public BeefProduction cattleBreed(CattleBreedEnum cattleBreed) {
    this.cattleBreed = cattleBreed;
    return this;
  }

  /**
   * breed of the animal
   * @return cattleBreed
  */

  @Schema(name = "cattleBreed", description = "breed of the animal", required = false)
  public CattleBreedEnum getCattleBreed() {
    return cattleBreed;
  }

  public void setCattleBreed(CattleBreedEnum cattleBreed) {
    this.cattleBreed = cattleBreed;
  }

  public BeefProduction birthDate(LocalDate birthDate) {
    this.birthDate = birthDate;
    return this;
  }

  /**
   * date when the animal is born
   * @return birthDate
  */
  @Valid
  @Schema(name = "birthDate", description = "date when the animal is born", required = false)
  public LocalDate getBirthDate() {
    return birthDate;
  }

  public void setBirthDate(LocalDate birthDate) {
    this.birthDate = birthDate;
  }

  public BeefProduction birthPlace(String birthPlace) {
    this.birthPlace = birthPlace;
    return this;
  }

  /**
   * place where the animal is born
   * @return birthPlace
  */
  
  @Schema(name = "birthPlace", description = "place where the animal is born", required = false)
  public String getBirthPlace() {
    return birthPlace;
  }

  public void setBirthPlace(String birthPlace) {
    this.birthPlace = birthPlace;
  }

  public BeefProduction birthFarm(String birthFarm) {
    this.birthFarm = birthFarm;
    return this;
  }

  /**
   * farming company where the animal is born
   * @return birthFarm
  */

  @Schema(name = "birthFarm", description = "farming company where the animal is born", required = false)
  public String getBirthFarm() {
    return birthFarm;
  }

  public void setBirthFarm(String birthFarm) {
    this.birthFarm = birthFarm;
  }

  public BeefProduction warmCarcassWeight(Integer warmCarcassWeight) {
    this.warmCarcassWeight = warmCarcassWeight;
    return this;
  }

  /**
   * weight of the animal just after being killed, in kilograms
   * @return warmCarcassWeight
  */

  @Schema(name = "warmCarcassWeight", description = "weight of the animal just after being killed, in kilograms", required = false)
  public Integer getWarmCarcassWeight() {
    return warmCarcassWeight;
  }

  public void setWarmCarcassWeight(Integer warmCarcassWeight) {
    this.warmCarcassWeight = warmCarcassWeight;
  }

  public BeefProduction meatWeight(Integer meatWeight) {
    this.meatWeight = meatWeight;
    return this;
  }

  /**
   * weight of meat predicted, in kilograms
   * @return meatWeight
  */

  @Schema(name = "meatWeight", description = "weight of meat predicted, in kilograms", required = false)
  public Integer getMeatWeight() {
    return meatWeight;
  }

  public void setMeatWeight(Integer meatWeight) {
    this.meatWeight = meatWeight;
  }

  public BeefProduction slaughterDate(LocalDate slaughterDate) {
    this.slaughterDate = slaughterDate;
    return this;
  }

  /**
   * date when the animal has been killed
   * @return slaughterDate
  */
  @Valid
  @Schema(name = "slaughterDate", description = "date when the animal has been killed", required = false)
  public LocalDate getSlaughterDate() {
    return slaughterDate;
  }

  public void setSlaughterDate(LocalDate slaughterDate) {
    this.slaughterDate = slaughterDate;
  }

  public BeefProduction slaughterPlace(String slaughterPlace) {
    this.slaughterPlace = slaughterPlace;
    return this;
  }

  /**
   * the place where the animal has been killed
   * @return slaughterPlace
  */

  @Schema(name = "slaughterPlace", description = "the place where the animal has been killed", required = false)
  public String getSlaughterPlace() {
    return slaughterPlace;
  }

  public void setSlaughterPlace(String slaughterPlace) {
    this.slaughterPlace = slaughterPlace;
  }

  public BeefProduction slaughterHouse(String slaughterHouse) {
    this.slaughterHouse = slaughterHouse;
    return this;
  }

  /**
   * the company where the animal has been killed
   * @return slaughterHouse
  */

  @Schema(name = "slaughterHouse", description = "the company where the animal has been killed", required = false)
  public String getSlaughterHouse() {
    return slaughterHouse;
  }

  public void setSlaughterHouse(String slaughterHouse) {
    this.slaughterHouse = slaughterHouse;
  }

  public BeefProduction cuttingDate(String cuttingDate) {
    this.cuttingDate = cuttingDate;
    return this;
  }

  /**
   * date when the animal has been cutted
   * @return cuttingDate
  */

  @Schema(name = "cuttingDate", description = "date when the animal has been cutted", required = false)
  public String getCuttingDate() {
    return cuttingDate;
  }

  public void setCuttingDate(String cuttingDate) {
    this.cuttingDate = cuttingDate;
  }

  public BeefProduction cuttingPlace(String cuttingPlace) {
    this.cuttingPlace = cuttingPlace;
    return this;
  }

  /**
   * the place where the animal has been cutted
   * @return cuttingPlace
  */

  @Schema(name = "cuttingPlace", description = "the place where the animal has been cutted", required = false)
  public String getCuttingPlace() {
    return cuttingPlace;
  }

  public void setCuttingPlace(String cuttingPlace) {
    this.cuttingPlace = cuttingPlace;
  }

  public BeefProduction cuttingButcher(String cuttingButcher) {
    this.cuttingButcher = cuttingButcher;
    return this;
  }

  /**
   * butcher company where the animal has been cutted
   * @return cuttingButcher
  */

  @Schema(name = "cuttingButcher", description = "butcher company where the animal has been cutted", required = false)
  public String getCuttingButcher() {
    return cuttingButcher;
  }

  public void setCuttingButcher(String cuttingButcher) {
    this.cuttingButcher = cuttingButcher;
  }

  public BeefProduction labelRougeCertified(Boolean labelRougeCertified) {
    this.labelRougeCertified = labelRougeCertified;
    return this;
  }

  /**
   * true if the animal breeding process matches the french 'label rouge certification
   * @return labelRougeCertified
  */

  @Schema(name = "labelRougeCertified", description = "true if the animal breeding process matches the french 'label rouge certification", required = false)
  public Boolean getLabelRougeCertified() {
    return labelRougeCertified;
  }

  public void setLabelRougeCertified(Boolean labelRougeCertified) {
    this.labelRougeCertified = labelRougeCertified;
  }

  public BeefProduction id(Integer id) {
    super.setId(id);
    return this;
  }

  public BeefProduction productionType(ProductionTypeEnum productionType) {
    super.setProductionType(productionType);
    return this;
  }

  public BeefProduction sales(List<Sale> sales) {
    super.setSales(sales);
    return this;
  }

  public BeefProduction addSalesItem(Sale salesItem) {
    super.addSalesItem(salesItem);
    return this;
  }

  public BeefProduction producer(Producer producer) {
    super.setProducer(producer);
    return this;
  }

  public BeefProduction lots(List<PackageLot> lots) {
    super.setLots(lots);
    return this;
  }

  public BeefProduction addLotsItem(PackageLot lotsItem) {
    super.addLotsItem(lotsItem);
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BeefProduction beefProduction = (BeefProduction) o;
    return Objects.equals(this.animalIdentifier, beefProduction.animalIdentifier) &&
        Objects.equals(this.animalType, beefProduction.animalType) &&
        Objects.equals(this.cattleBreed, beefProduction.cattleBreed) &&
        Objects.equals(this.birthDate, beefProduction.birthDate) &&
        Objects.equals(this.birthPlace, beefProduction.birthPlace) &&
        Objects.equals(this.birthFarm, beefProduction.birthFarm) &&
        Objects.equals(this.warmCarcassWeight, beefProduction.warmCarcassWeight) &&
        Objects.equals(this.meatWeight, beefProduction.meatWeight) &&
        Objects.equals(this.slaughterDate, beefProduction.slaughterDate) &&
        Objects.equals(this.slaughterPlace, beefProduction.slaughterPlace) &&
        Objects.equals(this.slaughterHouse, beefProduction.slaughterHouse) &&
        Objects.equals(this.cuttingDate, beefProduction.cuttingDate) &&
        Objects.equals(this.cuttingPlace, beefProduction.cuttingPlace) &&
        Objects.equals(this.cuttingButcher, beefProduction.cuttingButcher) &&
        Objects.equals(this.labelRougeCertified, beefProduction.labelRougeCertified) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(animalIdentifier, animalType, cattleBreed, birthDate, birthPlace, birthFarm, warmCarcassWeight, meatWeight, slaughterDate, slaughterPlace, slaughterHouse, cuttingDate, cuttingPlace, cuttingButcher, labelRougeCertified, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BeefProduction {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    animalIdentifier: ").append(toIndentedString(animalIdentifier)).append("\n");
    sb.append("    animalType: ").append(toIndentedString(animalType)).append("\n");
    sb.append("    cattleBreed: ").append(toIndentedString(cattleBreed)).append("\n");
    sb.append("    birthDate: ").append(toIndentedString(birthDate)).append("\n");
    sb.append("    birthPlace: ").append(toIndentedString(birthPlace)).append("\n");
    sb.append("    birthFarm: ").append(toIndentedString(birthFarm)).append("\n");
    sb.append("    warmCarcassWeight: ").append(toIndentedString(warmCarcassWeight)).append("\n");
    sb.append("    meatWeight: ").append(toIndentedString(meatWeight)).append("\n");
    sb.append("    slaughterDate: ").append(toIndentedString(slaughterDate)).append("\n");
    sb.append("    slaughterPlace: ").append(toIndentedString(slaughterPlace)).append("\n");
    sb.append("    slaughterHouse: ").append(toIndentedString(slaughterHouse)).append("\n");
    sb.append("    cuttingDate: ").append(toIndentedString(cuttingDate)).append("\n");
    sb.append("    cuttingPlace: ").append(toIndentedString(cuttingPlace)).append("\n");
    sb.append("    cuttingButcher: ").append(toIndentedString(cuttingButcher)).append("\n");
    sb.append("    labelRougeCertified: ").append(toIndentedString(labelRougeCertified)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

