name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/app
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.12.1
      uses: actions/setup-node@v4
      with:
        node-version: 20.2.0
        cache: 'npm'
        cache-dependency-path: frontend/app
    - run: npm install @openapitools/openapi-generator-cli@2.6.0 -g
    - run: npm run generate:api
    - run: npm run build:api
    - run: npm run install:api
    - run: npm ci
    - run: npm run build --if-present
      env:
        CI: false
    - run: npm test
      
