name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/app
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.2.0
      uses: actions/setup-node@v4
      with:
        node-version: 20.2.0
        cache: 'npm'
        cache-dependency-path: frontend/app
    - name: Install js openapi-generator client
      run: npm install @openapitools/openapi-generator-cli@2.6.0 -g
    - name: Generate js code from openapi
      run: 
        cd ../..
        bash scripts/dev/generate-client-code-from-openapi.sh
    - name: Clean and install dependencies
      run: npm ci
    - name: Build js app
      run: npm run build --if-present
      env:
        CI: false
    - name: Run jest js tests
      run: npm test
      
