name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.12.1
      uses: actions/setup-node@v3
      with:
        node-version: 18.12.1
        cache: 'npm'
    - working-directory: ./viandeendirect/frontend/app
      run: npm ci
    - working-directory: ./viandeendirect/frontend/app
      run: npm run build --if-present
    - working-directory: ./viandeendirect/frontend/app
      run: npm test
